// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/uk-health-visa/HealthVisaApplication.tsx": () => import("../components/mockups/uk-health-visa/HealthVisaApplication.tsx")
};
